### ISSUE TITLE
Netlify app down?

### ISSUE THREAD

**Issue by keeganquigley** [Phala-Network/oracle-workshop#3]
Hi, the UI seems to be down for this tutorial:

![badges](https://user-images.githubusercontent.com/35080151/209032848-4224c694-6329-4280-af3d-a063f88b0bf6.png)

It doesn't work in any browser. The faucet does seem to work, however. What am I missing? Thanks!

**Comment by h4x3rotab** [comment]
Hi! Thanks for the feedback. Currently this version of the workshop is not actively maintained. We have upgraded it to the new Sub0 2022 workshop with better technologies. You can find it [here](https://github.com/Phala-Network/phat-offchain-rollup/tree/sub0-workshop/phat).

Where did you hear this old workshop? Do you think it's better to keep it maintained? We can probably fix it if you think it's valuable.

**Comment by keeganquigley** [comment]
@h4x3rotab sorry for the late reply, I heard about this workshop at Sub0, so that's the one I was looking for. I had the wrong link apparently. I will try with this one. Thanks!
