### ISSUE TITLE
Easy Challenge Frontend loading issue (Error: No contract key)

### ISSUE THREAD

**Issue by LachPawel** [Phala-Network/oracle-workshop#4]
When I try to do the challenges the loading spinner keeps loading, and I get the following error in the console.

```
Uncaught (in promise) Error: 
No contract key for 0xe3ba6fc43c1477ab2974a3bd1fba718707b610e1e90a9074e3eb981be864f3c0
```

Of course I do have GH and Polkadot.js account, I sign in with Polkadot and select account but it doesn't fix anything. 

Screenshot below

<img width="1369" alt="Screenshot 2023-02-07 at 21 54 17" src="https://user-images.githubusercontent.com/53332984/217363313-710399dc-c68a-4776-a26f-8b36641a879c.png">

**Comment by LachPawel** [comment]
The same happens in Advanced Challenge, FYI

**Comment by h4x3rotab** [comment]
Thanks for your interest in the workshop. However this workshop is deprecated. We have upgraded it to the Sub0 2022 oracle workshop, which guides you how to deploy an oracle that works with Substrate and EVM. Please check it out: <https://github.com/Phala-Network/phat-offchain-rollup/blob/main/phat/Sub0-Workshop.md>

**Comment by LachPawel** [comment]
Great, thanks for the info! :)
